cunit_test:
  stage: test
  image: gcc:latest
  before_script:
    - apt-get update && apt-get install -y libcunit1-dev libncurses-dev
  script:
    - cd cunit
    - make
    - ./riscv_test.bin
  artifacts:
    when: always
    reports:
      junit: Init-Results.xml